### PR TITLE
listmode DL notebooks for PSMR 2024

### PR DESCRIPTION
**Pull request by gschramm**
**Don't merge yet, because:**
- first needs merging of SIRF PR https://github.com/SyneRBI/SIRF/pull/1253
- clean-up files + final conversion of ??_*.py notebooks to jupyter notebook

### CODE REVIEW

**Comment by gschramm** [comment]
@KrisThielemans for adding the LM caching: 
-  [here](https://github.com/gschramm/SIRF-Exercises/blob/2cdda25975855a4e4c96be8f5507b2712c73e2df/notebooks/Deep_Learning_listmode_PET/01_SIRF_listmode_recon.py#L60) is where I setup the `ListModeData` object
- [here](https://github.com/gschramm/SIRF-Exercises/blob/2cdda25975855a4e4c96be8f5507b2712c73e2df/notebooks/Deep_Learning_listmode_PET/01_SIRF_listmode_recon.py#L314) is where I setup the listmode logL and reconstruct

**Comment by gschramm** [comment]
1. Isn't it the easiest / most efficient if we only unlist + reconstruct the complete (1m and 60min) list mode files. Should avoid all kind of problems ...
2. is the "large number" in bytes / MB / GB?
3. Just starting reconstructing the 60min data after downloading. But I immediately get this error when reading the mumap file:
```python
attn_image = sirf.STIR.ImageData("../../data/PET/mMR/NEMA_IQ/20170809_NEMA_MUMAP_UCL.v.hdr")

error: ??? '\'\\nERROR: Error parsing: expected a vectorised key as in "image duration (sec)[1]", but no bracket found\\n\' 
exception caught at line 417 of /users/nexuz/gschra2/nge/SIRF/build_lm/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp; the reconstruction engine output may provide more information'
```

The header looks like this:
```
!IMAGE DATA DESCRIPTION:=
!total number of data sets:=1
!image duration (sec):=0
!image relative start time (sec):=0
```

**Comment by KrisThielemans** [comment]
1. sure
2. bytes
3. yes, the full notebook contains extra stuff to handle this, but easiest is to use the same attenuation image and norm (or indeed acq_sens_model) as for the 1 min data. Note that there will be scale factor of 60 (or nearly, due to decay) between the images, as that's currently not yet taken into account.

**Comment by gschramm** [comment]
Thanks Kris! Will update the notebooks accoordingly tmr.
To take care of the scale difference for the 60min ref. image, I will probably just rescale based on the mean intensity.

**Comment by KrisThielemans** [comment]
I'll merge this in a few minutes

**Comment by gschramm** [comment]
ready to be merged

**Comment by KrisThielemans** [comment]
squash or not? As you prefer

**Comment by gschramm** [comment]
please squash, but let me fix one typo before

**Comment by gschramm** [comment]
@KrisThielemans : typos fixed, ready to be squashed and merged

**Pull request merged**
