### PR TITLE
New geometry notebooks

### PR DESCRIPTION
**Pull request by DANAJK**
New geometry notebooks. Need copyright adding and possibly modifying data path. See get_nifti_data notebook for Zenodo location of data

### CODE REVIEW

**Comment by KrisThielemans** [comment]
thanks @DANAJK ... illuminating...

I'm updating the download location. Will push that soon.

**Comment by KrisThielemans** [comment]
Question after looking at `a_geometry`. I don't think that in the first part you actually say which coordinate corresponds to `L`. For instance is `IPP[0]` `L`, or `IPP[2]`?

Obviously related is the question what @rijobro intended when reversing the order noted in https://github.com/SyneRBI/SIRF/issues/906#issuecomment-865640054

**Comment by KrisThielemans** [comment]
pushed. I'm trying to see how it works when reading with `sirf.STIR`. If that works ok, I'll push that as well and then merge.

**Comment by KrisThielemans** [comment]
works ok, except that it fails on the oblique slices. I've added a warning.

Ready to merge?

**Comment by DANAJK** [comment]
`To do this, it needs to know the patient position. This is available in DICOM data, but unfortunately not for NIfTI.` 
The DICOM IPP, IOP etc can be computed from NIfTI data as shown in one of these notebooks. Maybe better to say that STIR and some other reconstructions set dummy values, so BEWARE?

**Comment by KrisThielemans** [comment]
> Obviously related is the question what @rijobro intended when reversing the order noted in [SyneRBI/SIRF#906 (comment)](https://github.com/SyneRBI/SIRF/issues/906#issuecomment-865640054)

Wrongly attributing to @rijobro here. Sorry. Discussion at https://github.com/SyneRBI/SIRF/issues/906#issuecomment-865640054

**Comment by KrisThielemans** [comment]
@DANAJK would you be able to create a `README` for this directory? If you use links to names of notebooks, it makes it easy for people to open them from there (currently only on GitHub, but presumably soon when using JupyterLab).

Do any of the registration notebooks need changing? If so, want to create some issues and even tackle it?

I suggest to merge this PR already such that it ends up in future builds of docker etc.

**Comment by KrisThielemans** [comment]
@danajk, could you shed some light on https://github.com/SyneRBI/SIRF-Exercises/pull/111#issuecomment-865647282? With the example data that you give, it really isn't clear which is which (at least to me).

**Comment by DANAJK** [comment]
IPP[0] is L. I could perhaps include a screenshot from OsiriX that labels the directions so that it is more obvious which phantom is where?

I don't know what to do with registration notebook - it has multiple areas that need addressing (cubic example, mis-leading flipping, test niftis that differ in scale as well as translation and orientation).

**Comment by KrisThielemans** [comment]
> IPP[0] is L. I could perhaps include a screenshot from OsiriX that labels the directions so that it is more obvious which phantom is where?

great. what about just stating that? Whatever is easiest.

**Comment by KrisThielemans** [comment]
> I don't know what to do with registration notebook - it has multiple areas that need addressing (cubic example, mis-leading flipping, test niftis that differ in scale as well as translation and orientation).

hmm. 

what about 
- cutting the "A little word about image orientation" section (and referring to one of your new notebooks)
- adding a caveat in the displacement fields that currently they have RAS coordinates (could refer to https://github.com/SyneRBI/SIRF/issues/721), but otherwise leave it as-is.

That might do the trick? Obviously would be better to have non-cubic images etc, but there's little doubt that the code will work with them, so I wouldn't try to do that now!

**Comment by KrisThielemans** [comment]
@DANAJK I'll merge this now. You can always fine-tune. The main thing that is missing is a README that explains what each notebook does (one-liner).

thanks a lot

**Pull request merged**
