### PR TITLE
Zenodo saved trained model and results

### PR DESCRIPTION
**Pull request by Imraj-Singh**
downloading from zenodo although there are no check to see if the file downloaded correctly. Could add this to the download_data.sh script instead?

### CODE REVIEW

**Comment by danieldeidda** [comment]
Thanks! is this ready to be merged?

**Comment by KrisThielemans** [comment]
not sure, but I think there's some extra stuff here because you don't have `nbstripout` installed. @Imraj-Singh can you manually run it and see if it makes any difference?

**Comment by Imraj-Singh** [comment]
Hi @KrisThielemans, I did install it prior to adding, commiting and pushing that changed notebook. I ran `nbstripout 4_setup_training.ipynb`. I reran `nbstripout 4_setup_training.ipynb`, git added and it does not seem like it made a difference. Is there anything else I can do?

**Comment by KrisThielemans** [comment]
I'll merge it. @samdporter can then complain later :-)

**Pull request merged**
