### PR TITLE
Fix mapem explode

### LINKED ISSUE #96: MAPEM Notebook results explode
image

_Originally posted by @ashgillman in https://github.com/SyneRBI/SIRF-Exercises/issues/94#issuecomment-856709022_

### PR DESCRIPTION
**Pull request by ashgillman**
Fix #96

No more NaNs

image

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I guess this needs to be rebased

**Comment by ashgillman** [comment]
Whoops, I guess I was in a rush. Fixed

**Comment by KrisThielemans** [comment]
thanks. It could be useful to draw some attention to this in a doc-cell. I don't think that the original paper has this "epsilon". I believe it is necessary because of OSEM.

**Comment by ashgillman** [comment]
I'm not 100% sure why subsets would impact this update, which is in image space (that's in no way to say I doubt it!). But logically, if locally x_reg = 1 and x_em = 0 then you'd get the denominator = 0, so it seems pretty reasonable that that could occur and that the eps is a good idea. I've added a fairly generic explanation - do you think it's adequate?

**Comment by KrisThielemans** [comment]
sure.

I believe that if you initialise the algo with non-zero, and you use 1 subset, it can never get to this case, but it's ages ago I've checked that or indeed read the paper. Happy with your modification.

**Pull request merged**
