### PR TITLE
Lm DL updates

### PR DESCRIPTION
**Pull request by gschramm**
- store "temporary" sinograms not in $HOME, but in a subdir of `examples_path("PET")` to avoid disk space problems
- remove 60min recon exercise because it takes to long. recon will be provided instead ...
- update documentation

### CODE REVIEW

**Comment by gschramm** [comment]
@KrisThielemans new PR changes storage location of "temp" sinograms + update of documentation

**Comment by KrisThielemans** [comment]
Is the notebook written such that it could apply with some mods for people later on (without cloud access). can leave that for later of course!

A bit strange the `id` changed, but it doesn't matter. Did you run `nbstripout`?

**Comment by gschramm** [comment]
1. everything works "offline" as well. tested it locally and on the stfc cloud. Is storing data in `Path(examples_data_path("PET")) / "mMR" / "lm_recons_1min"` not a good idea?
2. The ids changed because I deleted the notebooks and re-created them :(
`jupytext` has an option to keep them, but not if you re-create them

**Comment by gschramm** [comment]
@KrisThielemans there will be one last change coming once I know where Edo puts the files we sent him this morning.
But I think it is better to merge now, and do a separate mini PR tomorrow 
(or we simply tell the training school participants to manually change 1 file path in the notebook)

(using that for the 60min LM data recon that takes long). Offline users, can run those themselves, but I prefer to have them pre-installed for the training school to save time.

**Comment by KrisThielemans** [comment]
ok. no problem. I'll merge!

**Pull request merged**
