### PR TITLE
Use numba @jit by default now we're using Py3.

### PR DESCRIPTION
**Pull request by ashgillman**
Also remove pip installs already handled by requirements.txt.

### CODE REVIEW

**Comment by ashgillman** [comment]
Sorry - an extra small change snuck in I didn't mean to commit - I changed the rotation from 30 degrees to 10. But the 30 degrees is a bit dramatic, are you happy to keep it?

https://github.com/SyneRBI/SIRF-Exercises/pull/79/files#diff-b4d907aa1cf552f3169938ef18c99c04a5739fe68855b563fcee0f9a772de665R354

**Comment by ashgillman** [comment]
A lot of cell metadata has also made it through.. Is this typical?
I ran the `nbstripoutput` lines in the INSTALL.MD

**Comment by ashgillman** [comment]
Fixes #64

**Comment by KrisThielemans** [comment]
> Sorry - an extra small change snuck in I didn't mean to commit - I changed the rotation from 30 degrees to 10.

fine for me

**Comment by ashgillman** [comment]
> I'm assuming you ran this?

Yes 👍

**Pull request merged**
