### PR TITLE
First implementation of the Deep Learning notebooks, with SIRF wrappers.

### PR DESCRIPTION
**Pull request by Imraj-Singh**
The main problem is the computational time needed to train. Perhaps worth giving participants a pre-trained model (or quasi-trained), and during the training session we can get them to run inference of the model.

### CODE REVIEW

**Review by KrisThielemans — COMMENTED** [review]
I didn't check this really, but at first glance, you have not used `nbstripout`, see https://github.com/SyneRBI/SIRF-Exercises/blob/master/INSTALL.md#updating-the-exercises-after-installation

as you have already commited, I think the process now is to
1.  run `nbstripout` on each notebook
2. `git commit`
3. run the `install` and `config` commands
4. `git status` should say no changes

If it shows differences, I think the best thing to do would be to start from scratch, i.e. 
1. run the `install` and `config` commands
2. create a new branch
3. copy your new files by hand to this branch
4. `git commit`
5. `git status` should say no changes
6. create new PR and close this one

**Comment by Imraj-Singh** [comment]
Hi @KrisThielemans, I've done this now and there were no changes. I did strip the notebook outputs by hand previously and wasn't aware of the `nbstripout`, my apologies. Is this okay now? Thanks, Imraj

**Comment by Imraj-Singh** [comment]
@KrisThielemans made the changes you suggest in our chat. Okay to merge?

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
I think it would be best to add more info on the README with that is, a pointer to the paper etc.
Want to do that later?

What about adding as exercise: use "realistic" acquisition model for training data generation, but "simple" acquisition model for reconstruction.

**Comment by KrisThielemans** [comment]
Possibly you address a few of the Codacy issues. This link might work
https://app.codacy.com/gh/SyneRBI/SIRF-Exercises/pullRequest?_ga=2.232672095.1548072879.1653313615-268825818.1653313615

a lot is trailing white space or docstring stuff. Addressing a few would be good, but not essential

**Comment by Imraj-Singh** [comment]
I changed my trained network to a 5 iteration case, also implemented the changes suggested by you and codacy.

**Review by KrisThielemans — APPROVED** [review]

**Pull request merged**
